---
title: "Sex-ratio-bargaining"
author: "Rubén Pérez Sanz"
date: "2023-08-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
```

# Sex-ratio and Bargaining

The main purpose of this document is to have an idea of how the sex ration in the 
negotiating table affects to clauses negotiated in CA that relate to Family welfare
and equality

## Setting

### Load

The libraries that I will need:

```{r load-packages, message = FALSE}
library(dplyr)
library(ggplot2)
library(statsr)
library(readxl)
library(expss)
library(stringr)
library(zoo)
library(erer)
```

### Define the paths

```{r pahts}
dell <- 0 
if (dell == 1) {
    computer <- "C:/Users/jj22684/"
} else {
    computer <- "C:/Users/lenovo/"
}

setwd(paste0(computer,"Dropbox/PROJECTS/06. CAandfirms/Work/R/Analysis - Rmarkdown"))
Main_path   <- paste(computer, "Dropbox/PROJECTS/06. CAandfirms/Work/R/Analysis - Rmarkdown", sep = "")
raw_path	<- paste(computer, "Dropbox/PROJECTS/06. CAandfirms/Work/R/build", sep = "")
```

### Load the database

```{r load-abrbuthnot-data}
load(paste(raw_path, "/tufwf_built.R", sep = ""))
```
# Describe variables

```{r Plot nature vs informed, echo=FALSE}
tufwf2 <- tufwf %>% select(c('familybalance','workingday_adapt','workingday_reduction2','sumcnmales','sumcnfemales','sizem','sizew')) %>% 
                mutate(cnfemratio = sumcnfemales/(sumcnmales+sumcnfemales)) %>%
                mutate(femratio = sizew/(sizew+sizem))
#REGCON_FIRM2 %>% 
ggplot(data = tufwf2,aes(x = familybalance, fill = familybalance)) +
    geom_bar(show.legend = FALSE) +
    labs(y = "Frequency", x = "Number of CA that include measures to facilittate family welfare")

ggplot(data = tufwf2, aes(x = familybalance, fill = workingday_adapt)) +
    geom_bar(position = "stack",show.legend = TRUE) +
    labs(y = "Frequency", x = "Number of CA that include measures to facilittate family welfare") 

ggplot(data = tufwf2, aes(x = familybalance, fill = workingday_reduction2)) +
    geom_bar(position = "stack",show.legend = TRUE) +
    labs(y = "Frequency", x = "Number of CA that include measures to facilittate family welfare") 

mylogit <- glm(familybalance ~ femratio, data = tufwf2, family = binomial(link="logit"))
summary(mylogit)

mylogit2 <- glm(familybalance ~ cnfemratio + femratio + cnfemratio:femratio, data = tufwf2, family = binomial(link="logit"), x=TRUE)
summary(mylogit2)
ma <- maBina(w = mylogit2, x.mean = TRUE, rev.dum = TRUE)
ma


```
```{r Plot nature vs informed, echo=FALSE}
tufwf2 <- tufwf %>% select(c('breastfeeding'))
#REGCON_FIRM2 %>% 
ggplot(data = tufwf2,aes(x = breastfeeding, fill = breastfeeding)) +
    geom_bar(show.legend = FALSE) +
    labs(y = "Frequency", x = "CA allows teh right to accumulate breast feeding")
```
