labelcnae <- function(cnae4,level) {
    cnae4 <- as.numeric(as.character(cnae4))
    if (level == 1) {
        cnae1 = factor(floor(cnae4/100))
        V <- factor(cnae1,
            levels = c(
                1,
                2,
                3,
                5,
                6,
                7,
                8,
                9,
                10,
                11,
                12,
                13,
                14,
                15,
                16,
                17,
                18,
                19,
                20,
                21,
                22,
                23,
                24,
                25,
                26,
                27,
                28,
                29,
                30,
                31,
                32,
                33,
                35,
                36,
                37,
                38,
                39,
                41,
                42,
                43,
                45,
                46,
                47,
                49,
                50,
                51,
                52,
                53,
                55,
                56,
                58,
                59,
                60,
                61,
                62,
                63,
                64,
                65,
                66,
                68,
                69,
                70,
                71,
                72,
                73,
                74,
                75,
                77,
                78,
                79,
                80,
                81,
                82,
                84,
                85,
                86,
                87,
                88,
                90,
                91,
                92,
                93,
                94,
                95,
                96,
                97,
                98,
                99
            ),
            labels = c(
                "AGRICULTURE, FORESTRY AND FISHING",
                "AGRICULTURE, FORESTRY AND FISHING",
                "AGRICULTURE, FORESTRY AND FISHING",
                "MINING AND QUARRYING",
                "MINING AND QUARRYING",
                "MINING AND QUARRYING",
                "MINING AND QUARRYING",
                "MINING AND QUARRYING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "MANUFACTURING",
                "ELECTRICITY, GAS, STEAM AND AIR CONDITIONING SUPPLY",
                "WATER SUPPLY; SEWERAGE, WASTE MANAGEMENT AND REMEDIATION ACTIVITIES",
                "WATER SUPPLY; SEWERAGE, WASTE MANAGEMENT AND REMEDIATION ACTIVITIES",
                "WATER SUPPLY; SEWERAGE, WASTE MANAGEMENT AND REMEDIATION ACTIVITIES",
                "WATER SUPPLY; SEWERAGE, WASTE MANAGEMENT AND REMEDIATION ACTIVITIES",
                "CONSTRUCTION",
                "CONSTRUCTION",
                "CONSTRUCTION",
                "WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VEHICLES AND MOTORCYCLES",
                "WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VEHICLES AND MOTORCYCLES",
                "WHOLESALE AND RETAIL TRADE; REPAIR OF MOTOR VEHICLES AND MOTORCYCLES",
                "TRANSPORTATION AND STORAGE",
                "TRANSPORTATION AND STORAGE",
                "TRANSPORTATION AND STORAGE",
                "TRANSPORTATION AND STORAGE",
                "TRANSPORTATION AND STORAGE",
                "ACCOMMODATION AND FOOD SERVICE ACTIVITIES",
                "ACCOMMODATION AND FOOD SERVICE ACTIVITIES",
                "INFORMATION AND COMMUNICATION",
                "INFORMATION AND COMMUNICATION",
                "INFORMATION AND COMMUNICATION",
                "INFORMATION AND COMMUNICATION",
                "INFORMATION AND COMMUNICATION",
                "INFORMATION AND COMMUNICATION",
                "FINANCIAL AND INSURANCE ACTIVITIES",
                "FINANCIAL AND INSURANCE ACTIVITIES",
                "FINANCIAL AND INSURANCE ACTIVITIES",
                "REAL ESTATE ACTIVITIES",
                "PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",
                "PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",
                "PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",
                "PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",
                "PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",
                "PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",
                "PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES",
                "ADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIES",
                "ADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIES",
                "ADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIES",
                "ADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIES",
                "ADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIES",
                "ADMINISTRATIVE AND SUPPORT SERVICE ACTIVITIES",
                "PUBLIC ADMINISTRATION AND DEFENCE; COMPULSORY SOCIAL SECURITY",
                "EDUCATION",
                "HUMAN HEALTH AND SOCIAL WORK ACTIVITIES",
                "HUMAN HEALTH AND SOCIAL WORK ACTIVITIES",
                "HUMAN HEALTH AND SOCIAL WORK ACTIVITIES",
                "ARTS, ENTERTAINMENT AND RECREATION",
                "ARTS, ENTERTAINMENT AND RECREATION",
                "ARTS, ENTERTAINMENT AND RECREATION",
                "ARTS, ENTERTAINMENT AND RECREATION",
                "OTHER SERVICE ACTIVITIES",
                "OTHER SERVICE ACTIVITIES",
                "OTHER SERVICE ACTIVITIES",
                "ACTIVITIES OF HOUSEHOLDS AS EMPLOYERS; UNDIFFERENTIATED GOODS- AND SERVICES-PRODUCING ACTIVITIES OF HOUSEHOLDS FOR OWN USE",
                "ACTIVITIES OF HOUSEHOLDS AS EMPLOYERS; UNDIFFERENTIATED GOODS- AND SERVICES-PRODUCING ACTIVITIES OF HOUSEHOLDS FOR OWN USE",
                "ACTIVITIES OF EXTRATERRITORIAL ORGANISATIONS AND BODIES"
            )
        )
        
    } else if (level == 2) {
        cnae2 = factor(floor(cnae4/100))
        V <- factor(cnae2,
                levels = c(
                    1,
                    2,
                    3,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31,
                    32,
                    33,
                    35,
                    36,
                    37,
                    38,
                    39,
                    41,
                    42,
                    43,
                    45,
                    46,
                    47,
                    49,
                    50,
                    51,
                    52,
                    53,
                    55,
                    56,
                    58,
                    59,
                    60,
                    61,
                    62,
                    63,
                    64,
                    65,
                    66,
                    68,
                    69,
                    70,
                    71,
                    72,
                    73,
                    74,
                    75,
                    77,
                    78,
                    79,
                    80,
                    81,
                    82,
                    84,
                    85,
                    86,
                    87,
                    88,
                    90,
                    91,
                    92,
                    93,
                    94,
                    95,
                    96,
                    97,
                    98,
                    99
                ),
                labels = c(
                    "Crop and animal production, hunting and related service activities",
                    "Forestry and logging",
                    "Fishing and aquaculture",
                    "Mining of coal and lignite",
                    "Extraction of crude petroleum and natural gas",
                    "Mining of metal ores",
                    "Other mining and quarrying",
                    "Mining support service activities",
                    "Manufacture of food products",
                    "Manufacture of beverages",
                    "Manufacture of tobacco products",
                    "Manufacture of textiles",
                    "Manufacture of wearing apparel",
                    "Manufacture of leather and related products",
                    "Manufacture of wood and of products of wood and cork, except furniture; manufacture of articles of straw and plaiting materials",
                    "Manufacture of paper and paper products",
                    "Printing and reproduction of recorded media",
                    "Manufacture of coke and refined petroleum products",
                    "Manufacture of chemicals and chemical products",
                    "Manufacture of basic pharmaceutical products and pharmaceutical preparations",
                    "Manufacture of rubber and plastic products",
                    "Manufacture of other non-metallic mineral products",
                    "Manufacture of basic metals",
                    "Manufacture of fabricated metal products, except machinery and equipment",
                    "Manufacture of computer, electronic and optical products",
                    "Manufacture of electrical equipment",
                    "Manufacture of machinery and equipment n.e.c.",
                    "Manufacture of motor vehicles, trailers and semi-trailers",
                    "Manufacture of other transport equipment",
                    "Manufacture of furniture",
                    "Other manufacturing",
                    "Repair and installation of machinery and equipment",
                    "Electricity, gas, steam and air conditioning supply",
                    "Water collection, treatment and supply",
                    "Sewerage",
                    "Waste collection, treatment and disposal activities; materials recovery",
                    "Remediation activities and other waste management services",
                    "Construction of buildings",
                    "Civil engineering",
                    "Specialised construction activities",
                    "Wholesale and retail trade and repair of motor vehicles and motorcycles",
                    "Wholesale trade, except of motor vehicles and motorcycles",
                    "Retail trade, except of motor vehicles and motorcycles",
                    "Land transport and transport via pipelines",
                    "Water transport",
                    "Air transport",
                    "Warehousing and support activities for transportation",
                    "Postal and courier activities",
                    "Accommodation",
                    "Food and beverage service activities",
                    "Publishing activities",
                    "Motion picture, video and television programme production, sound recording and music publishing activities",
                    "Programming and broadcasting activities",
                    "Telecommunications",
                    "Computer programming, consultancy and related activities",
                    "Information service activities",
                    "Financial service activities, except insurance and pension funding",
                    "Insurance, reinsurance and pension funding, except compulsory social security",
                    "Activities auxiliary to financial services and insurance activities",
                    "Real estate activities",
                    "Legal and accounting activities",
                    "Activities of head offices; management consultancy activities",
                    "Architectural and engineering activities; technical testing and analysis",
                    "Scientific research and development",
                    "Advertising and market research",
                    "Other professional, scientific and technical activities",
                    "Veterinary activities",
                    "Rental and leasing activities",
                    "Employment activities",
                    "Travel agency, tour operator and other reservation service and related activities",
                    "Security and investigation activities",
                    "Services to buildings and landscape activities",
                    "Office administrative, office support and other business support activities",
                    "Public administration and defence; compulsory social security",
                    "Education",
                    "Human health activities",
                    "Residential care activities",
                    "Social work activities without accommodation",
                    "Creative, arts and entertainment activities",
                    "Libraries, archives, museums and other cultural activities",
                    "Gambling and betting activities",
                    "Sports activities and amusement and recreation activities",
                    "Activities of membership organisations",
                    "Repair of computers and personal and household goods",
                    "Other personal service activities",
                    "Activities of households as employers of domestic personnel",
                    "Undifferentiated goods- and services-producing activities of private households for own use",
                    "Activities of extraterritorial organisations and bodies"
                )
            )
                    
    } else if (level ==3)  {
        cnae3 = floor(cnae4/10)
        V <- factor(cnae3,
                levels = c(
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    21,
                    22,
                    23,
                    24,
                    31,
                    32,
                    51,
                    52,
                    61,
                    62,
                    71,
                    72,
                    81,
                    89,
                    91,
                    99,
                    101,
                    102,
                    103,
                    104,
                    105,
                    106,
                    107,
                    108,
                    109,
                    110,
                    120,
                    131,
                    132,
                    133,
                    139,
                    141,
                    142,
                    143,
                    151,
                    152,
                    161,
                    162,
                    171,
                    172,
                    181,
                    182,
                    191,
                    192,
                    201,
                    202,
                    203,
                    204,
                    205,
                    206,
                    211,
                    212,
                    221,
                    222,
                    231,
                    232,
                    233,
                    234,
                    235,
                    236,
                    237,
                    239,
                    241,
                    242,
                    243,
                    244,
                    245,
                    251,
                    252,
                    253,
                    254,
                    255,
                    256,
                    257,
                    259,
                    261,
                    262,
                    263,
                    264,
                    265,
                    266,
                    267,
                    268,
                    271,
                    272,
                    273,
                    274,
                    275,
                    279,
                    281,
                    282,
                    283,
                    284,
                    289,
                    291,
                    292,
                    293,
                    301,
                    302,
                    303,
                    304,
                    309,
                    310,
                    321,
                    322,
                    323,
                    324,
                    325,
                    329,
                    331,
                    332,
                    351,
                    352,
                    353,
                    360,
                    370,
                    381,
                    382,
                    383,
                    390,
                    411,
                    412,
                    421,
                    422,
                    429,
                    431,
                    432,
                    433,
                    439,
                    451,
                    452,
                    453,
                    454,
                    461,
                    462,
                    463,
                    464,
                    465,
                    466,
                    467,
                    469,
                    471,
                    472,
                    473,
                    474,
                    475,
                    476,
                    477,
                    478,
                    479,
                    491,
                    492,
                    493,
                    494,
                    495,
                    501,
                    502,
                    503,
                    504,
                    511,
                    512,
                    521,
                    522,
                    531,
                    532,
                    551,
                    552,
                    553,
                    559,
                    561,
                    562,
                    563,
                    581,
                    582,
                    591,
                    592,
                    601,
                    602,
                    611,
                    612,
                    613,
                    619,
                    620,
                    631,
                    639,
                    641,
                    642,
                    643,
                    649,
                    651,
                    652,
                    653,
                    661,
                    662,
                    663,
                    681,
                    682,
                    683,
                    691,
                    692,
                    701,
                    702,
                    711,
                    712,
                    721,
                    722,
                    731,
                    732,
                    741,
                    742,
                    743,
                    749,
                    750,
                    771,
                    772,
                    773,
                    774,
                    781,
                    782,
                    783,
                    791,
                    799,
                    801,
                    802,
                    803,
                    811,
                    812,
                    813,
                    821,
                    822,
                    823,
                    829,
                    841,
                    842,
                    843,
                    851,
                    852,
                    853,
                    854,
                    855,
                    856,
                    861,
                    862,
                    869,
                    871,
                    872,
                    873,
                    879,
                    881,
                    889,
                    900,
                    910,
                    920,
                    931,
                    932,
                    941,
                    942,
                    949,
                    951,
                    952,
                    960,
                    970,
                    981,
                    982
                ),
                labels = c(
                    "Growing of non-perennial crops",
                    "Growing of perennial crops",
                    "Plant propagation",
                    "Animal production",
                    "Mixed farming",
                    "Support activities to agriculture and post-harvest crop activities",
                    "Hunting, trapping and related service activities",
                    "Silviculture and other forestry activities",
                    "Logging",
                    "Gathering of wild growing non-wood products",
                    "Support services to forestry",
                    "Fishing",
                    "Aquaculture",
                    "Mining of hard coal",
                    "Mining of lignite",
                    "Extraction of crude petroleum",
                    "Extraction of natural gas",
                    "Mining of iron ores",
                    "Mining of non-ferrous metal ores",
                    "Quarrying of stone, sand and clay",
                    "Mining and quarrying n.e.c.",
                    "Support activities for petroleum and natural gas extraction",
                    "Support activities for other mining and quarrying",
                    "Processing and preserving of meat and production of meat products",
                    "Processing and preserving of fish, crustaceans and molluscs",
                    "Processing and preserving of fruit and vegetables",
                    "Manufacture of vegetable and animal oils and fats",
                    "Manufacture of dairy products",
                    "Manufacture of grain mill products, starches and starch products",
                    "Manufacture of bakery and farinaceous products",
                    "Manufacture of other food products",
                    "Manufacture of prepared animal feeds",
                    "Manufacture of beverages",
                    "Manufacture of tobacco products",
                    "Preparation and spinning of textile fibres",
                    "Weaving of textiles",
                    "Finishing of textiles",
                    "Manufacture of other textiles",
                    "Manufacture of wearing apparel, except fur apparel",
                    "Manufacture of articles of fur",
                    "Manufacture of knitted and crocheted apparel",
                    "Tanning and dressing of leather; manufacture of luggage, handbags, saddlery and harness; dressing and dyeing of fur",
                    "Manufacture of footwear",
                    "Sawmilling and planing of wood",
                    "Manufacture of products of wood, cork, straw and plaiting materials",
                    "Manufacture of pulp, paper and paperboard",
                    "Manufacture of articles of paper and paperboard",
                    "Printing and service activities related to printing",
                    "Reproduction of recorded media",
                    "Manufacture of coke oven products",
                    "Manufacture of refined petroleum products",
                    "Manufacture of basic chemicals, fertilisers and nitrogen compounds, plastics and synthetic rubber in primary forms",
                    "Manufacture of pesticides and other agrochemical products",
                    "Manufacture of paints, varnishes and similar coatings, printing ink and mastics",
                    "Manufacture of soap and detergents, cleaning and polishing preparations, perfumes and toilet preparations",
                    "Manufacture of other chemical products",
                    "Manufacture of man-made fibres",
                    "Manufacture of basic pharmaceutical products",
                    "Manufacture of pharmaceutical preparations",
                    "Manufacture of rubber products",
                    "Manufacture of plastic products",
                    "Manufacture of glass and glass products",
                    "Manufacture of refractory products",
                    "Manufacture of clay building materials",
                    "Manufacture of other porcelain and ceramic products",
                    "Manufacture of cement, lime and plaster",
                    "Manufacture of articles of concrete, cement and plaster",
                    "Cutting, shaping and finishing of stone",
                    "Manufacture of abrasive products and non-metallic mineral products n.e.c.",
                    "Manufacture of basic iron and steel and of ferro-alloys",
                    "Manufacture of tubes, pipes, hollow profiles and related fittings, of steel",
                    "Manufacture of other products of first processing of steel",
                    "Manufacture of basic precious and other non-ferrous metals",
                    "Casting of metals",
                    "Manufacture of structural metal products",
                    "Manufacture of tanks, reservoirs and containers of metal",
                    "Manufacture of steam generators, except central heating hot water boilers",
                    "Manufacture of weapons and ammunition",
                    "Forging, pressing, stamping and roll-forming of metal; powder metallurgy",
                    "Treatment and coating of metals; machining",
                    "Manufacture of cutlery, tools and general hardware",
                    "Manufacture of other fabricated metal products",
                    "Manufacture of electronic components and boards",
                    "Manufacture of computers and peripheral equipment",
                    "Manufacture of communication equipment",
                    "Manufacture of consumer electronics",
                    "Manufacture of instruments and appliances for measuring, testing and navigation; watches and clocks",
                    "Manufacture of irradiation, electromedical and electrotherapeutic equipment",
                    "Manufacture of optical instruments and photographic equipment",
                    "Manufacture of magnetic and optical media",
                    "Manufacture of electric motors, generators, transformers and electricity distribution and control apparatus",
                    "Manufacture of batteries and accumulators",
                    "Manufacture of wiring and wiring devices",
                    "Manufacture of electric lighting equipment",
                    "Manufacture of domestic appliances",
                    "Manufacture of other electrical equipment",
                    "Manufacture of general-purpose machinery",
                    "Manufacture of other general-purpose machinery",
                    "Manufacture of agricultural and forestry machinery",
                    "Manufacture of metal forming machinery and machine tools",
                    "Manufacture of other special-purpose machinery",
                    "Manufacture of motor vehicles",
                    "Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers",
                    "Manufacture of parts and accessories for motor vehicles",
                    "Building of ships and boats",
                    "Manufacture of railway locomotives and rolling stock",
                    "Manufacture of air and spacecraft and related machinery",
                    "Manufacture of military fighting vehicles",
                    "Manufacture of transport equipment n.e.c.",
                    "Manufacture of furniture",
                    "Manufacture of jewellery, bijouterie and related articles",
                    "Manufacture of musical instruments",
                    "Manufacture of sports goods",
                    "Manufacture of games and toys",
                    "Manufacture of medical and dental instruments and supplies",
                    "Manufacturing n.e.c.",
                    "Repair of fabricated metal products, machinery and equipment",
                    "Installation of industrial machinery and equipment",
                    "Electric power generation, transmission and distribution",
                    "Manufacture of gas; distribution of gaseous fuels through mains",
                    "Steam and air conditioning supply",
                    "Water collection, treatment and supply",
                    "Sewerage",
                    "Waste collection",
                    "Waste treatment and disposal",
                    "Materials recovery",
                    "Remediation activities and other waste management services",
                    "Development of building projects",
                    "Construction of residential and non-residential buildings",
                    "Construction of roads and railways",
                    "Construction of utility projects",
                    "Construction of other civil engineering projects",
                    "Demolition and site preparation",
                    "Electrical, plumbing and other construction installation activities",
                    "Building completion and finishing",
                    "Other specialised construction activities",
                    "Sale of motor vehicles",
                    "Maintenance and repair of motor vehicles",
                    "Sale of motor vehicle parts and accessories",
                    "Sale, maintenance and repair of motorcycles and related parts and accessories",
                    "Wholesale on a fee or contract basis",
                    "Wholesale of agricultural raw materials and live animals",
                    "Wholesale of food, beverages and tobacco",
                    "Wholesale of household goods",
                    "Wholesale of information and communication equipment",
                    "Wholesale of other machinery, equipment and supplies",
                    "Other specialised wholesale",
                    "Non-specialised wholesale trade",
                    "Retail sale in non-specialised stores",
                    "Retail sale of food, beverages and tobacco in specialised stores",
                    "Retail sale of automotive fuel in specialised stores",
                    "Retail sale of information and communication equipment in specialised stores",
                    "Retail sale of other household equipment in specialised stores",
                    "Retail sale of cultural and recreation goods in specialised stores",
                    "Retail sale of other goods in specialised stores",
                    "Retail sale via stalls and markets",
                    "Retail trade not in stores, stalls or markets",
                    "Passenger rail transport, interurban",
                    "Freight rail transport",
                    "Other passenger land transport",
                    "Freight transport by road and removal services",
                    "Transport via pipeline",
                    "Sea and coastal passenger water transport",
                    "Sea and coastal freight water transport",
                    "Inland passenger water transport",
                    "Inland freight water transport",
                    "Passenger air transport",
                    "Freight air transport and space transport",
                    "Warehousing and storage",
                    "Support activities for transportation",
                    "Postal activities under universal service obligation",
                    "Other postal and courier activities",
                    "Hotels and similar accommodation",
                    "Holiday and other short-stay accommodation",
                    "Camping grounds, recreational vehicle parks and trailer parks",
                    "Other accommodation",
                    "Restaurants and mobile food service activities",
                    "Event catering and other food service activities",
                    "Beverage serving activities",
                    "Publishing of books, periodicals and other publishing activities",
                    "Software publishing",
                    "Motion picture, video and television programme activities",
                    "Sound recording and music publishing activities",
                    "Radio broadcasting",
                    "Television programming and broadcasting activities",
                    "Wired telecommunications activities",
                    "Wireless telecommunications activities",
                    "Satellite telecommunications activities",
                    "Other telecommunications activities",
                    "Computer programming, consultancy and related activities",
                    "Data processing, hosting and related activities; web portals",
                    "Other information service activities",
                    "Monetary intermediation",
                    "Activities of holding companies",
                    "Trusts, funds and similar financial entities",
                    "Other financial service activities, except insurance and pension funding",
                    "Insurance",
                    "Reinsurance",
                    "Pension funding",
                    "Activities auxiliary to financial services, except insurance and pension funding",
                    "Activities auxiliary to insurance and pension funding",
                    "Fund management activities",
                    "Buying and selling of own real estate",
                    "Rental and operating of own or leased real estate",
                    "Real estate activities on a fee or contract basis",
                    "Legal activities",
                    "Accounting, bookkeeping and auditing activities; tax consultancy",
                    "Activities of head offices",
                    "Management consultancy activities",
                    "Architectural and engineering activities and related technical consultancy",
                    "Technical testing and analysis",
                    "Research and experimental development on natural sciences and engineering",
                    "Research and experimental development on social sciences and humanities",
                    "Advertising",
                    "Market research and public opinion polling",
                    "Specialised design activities",
                    "Photographic activities",
                    "Translation and interpretation activities",
                    "Other professional, scientific and technical activities n.e.c.",
                    "Veterinary activities",
                    "Rental and leasing of motor vehicles",
                    "Rental and leasing of personal and household goods",
                    "Rental and leasing of other machinery, equipment and tangible goods",
                    "Leasing of intellectual property and similar products, except copyrighted works",
                    "Activities of employment placement agencies",
                    "Temporary employment agency activities",
                    "Other human resources provision",
                    "Travel agency and tour operator activities",
                    "Other reservation service and related activities",
                    "Private security activities",
                    "Security systems service activities",
                    "Investigation activities",
                    "Combined facilities support activities",
                    "Cleaning activities",
                    "Landscape service activities",
                    "Office administrative and support activities",
                    "Activities of call centres",
                    "Organisation of conventions and trade shows",
                    "Business support service activities n.e.c.",
                    "Administration of the State and the economic and social policy of the community",
                    "Provision of services to the community as a whole",
                    "Compulsory social security activities",
                    "Pre-primary education",
                    "Primary education",
                    "Secondary education",
                    "Higher education",
                    "Other education",
                    "Educational support activities",
                    "Hospital activities",
                    "Medical and dental practice activities",
                    "Other human health activities",
                    "Residential nursing care activities",
                    "Residential care activities for mental retardation, mental health and substance abuse",
                    "Residential care activities for the elderly and disabled",
                    "Other residential care activities",
                    "Social work activities without accommodation for the elderly and disabled",
                    "Other social work activities without accommodation",
                    "Creative, arts and entertainment activities",
                    "Libraries, archives, museums and other cultural activities",
                    "Gambling and betting activities",
                    "Sports activities",
                    "Amusement and recreation activities",
                    "Activities of business, employers and professional membership organisations",
                    "Activities of trade unions",
                    "Activities of other membership organisations",
                    "Repair of computers and communication equipment",
                    "Repair of personal and household goods",
                    "Other personal service activities",
                    "Activities of households as employers of domestic personnel",
                    "Undifferentiated goods-producing activities of private households for own use",
                    "Undifferentiated service-producing activities of private households for own use"
                )
            )

    } else {
        V <- factor(cnae4,
                levels = c(
                    "0111",
                    "0112",
                    "0113",
                    "0114",
                    "0115",
                    "0116",
                    "0119",
                    "0121",
                    "0122",
                    "0123",
                    "0124",
                    "0125",
                    "0126",
                    "0127",
                    "0128",
                    "0129",
                    "0130",
                    "0141",
                    "0142",
                    "0143",
                    "0144",
                    "0145",
                    "0146",
                    "0147",
                    "0149",
                    "0150",
                    "0161",
                    "0162",
                    "0163",
                    "0164",
                    "0170",
                    "0210",
                    "0220",
                    "0230",
                    "0240",
                    "0311",
                    "0312",
                    "0321",
                    "0322",
                    "0510",
                    "0520",
                    "0610",
                    "0620",
                    "0710",
                    "0721",
                    "0729",
                    "0811",
                    "0812",
                    "0891",
                    "0892",
                    "0893",
                    "0899",
                    "0910",
                    "0990",
                    1011,
                    1012,
                    1013,
                    1021,
                    1022,
                    1031,
                    1032,
                    1039,
                    1042,
                    1043,
                    1044,
                    1052,
                    1053,
                    1054,
                    1061,
                    1062,
                    1071,
                    1072,
                    1073,
                    1081,
                    1082,
                    1083,
                    1084,
                    1085,
                    1086,
                    1089,
                    1091,
                    1092,
                    1101,
                    1102,
                    1103,
                    1104,
                    1105,
                    1106,
                    1107,
                    1200,
                    1310,
                    1320,
                    1330,
                    1391,
                    1392,
                    1393,
                    1394,
                    1395,
                    1396,
                    1399,
                    1411,
                    1412,
                    1413,
                    1414,
                    1419,
                    1420,
                    1431,
                    1439,
                    1511,
                    1512,
                    1520,
                    1610,
                    1621,
                    1622,
                    1623,
                    1624,
                    1629,
                    1711,
                    1712,
                    1721,
                    1722,
                    1723,
                    1724,
                    1729,
                    1811,
                    1812,
                    1813,
                    1814,
                    1820,
                    1910,
                    1920,
                    2011,
                    2012,
                    2013,
                    2014,
                    2015,
                    2016,
                    2017,
                    2020,
                    2030,
                    2041,
                    2042,
                    2051,
                    2052,
                    2053,
                    2059,
                    2060,
                    2110,
                    2120,
                    2211,
                    2219,
                    2221,
                    2222,
                    2223,
                    2229,
                    2311,
                    2312,
                    2313,
                    2314,
                    2319,
                    2320,
                    2331,
                    2332,
                    2341,
                    2342,
                    2343,
                    2344,
                    2349,
                    2351,
                    2352,
                    2361,
                    2362,
                    2363,
                    2364,
                    2365,
                    2369,
                    2370,
                    2391,
                    2399,
                    2410,
                    2420,
                    2431,
                    2432,
                    2433,
                    2434,
                    2441,
                    2442,
                    2443,
                    2444,
                    2445,
                    2446,
                    2451,
                    2452,
                    2453,
                    2454,
                    2511,
                    2512,
                    2521,
                    2529,
                    2530,
                    2540,
                    2550,
                    2561,
                    2562,
                    2571,
                    2572,
                    2573,
                    2591,
                    2592,
                    2593,
                    2594,
                    2599,
                    2611,
                    2612,
                    2620,
                    2630,
                    2640,
                    2651,
                    2652,
                    2660,
                    2670,
                    2680,
                    2711,
                    2712,
                    2720,
                    2731,
                    2732,
                    2733,
                    2740,
                    2751,
                    2752,
                    2790,
                    2811,
                    2812,
                    2813,
                    2814,
                    2815,
                    2821,
                    2822,
                    2823,
                    2824,
                    2825,
                    2829,
                    2830,
                    2841,
                    2849,
                    2891,
                    2892,
                    2893,
                    2894,
                    2895,
                    2896,
                    2899,
                    2910,
                    2920,
                    2931,
                    2932,
                    3011,
                    3012,
                    3020,
                    3030,
                    3040,
                    3091,
                    3092,
                    3099,
                    3101,
                    3102,
                    3103,
                    3109,
                    3211,
                    3212,
                    3213,
                    3220,
                    3230,
                    3240,
                    3250,
                    3291,
                    3299,
                    3311,
                    3312,
                    3313,
                    3314,
                    3315,
                    3316,
                    3317,
                    3319,
                    3320,
                    3512,
                    3513,
                    3514,
                    3515,
                    3516,
                    3517,
                    3518,
                    3519,
                    3521,
                    3522,
                    3523,
                    3530,
                    3600,
                    3700,
                    3811,
                    3812,
                    3821,
                    3822,
                    3831,
                    3832,
                    3900,
                    4110,
                    4121,
                    4122,
                    4211,
                    4212,
                    4213,
                    4221,
                    4222,
                    4291,
                    4299,
                    4311,
                    4312,
                    4313,
                    4321,
                    4322,
                    4329,
                    4331,
                    4332,
                    4333,
                    4334,
                    4339,
                    4391,
                    4399,
                    4511,
                    4519,
                    4520,
                    4531,
                    4532,
                    4540,
                    4611,
                    4612,
                    4613,
                    4614,
                    4615,
                    4616,
                    4617,
                    4618,
                    4619,
                    4621,
                    4622,
                    4623,
                    4624,
                    4631,
                    4632,
                    4633,
                    4634,
                    4635,
                    4636,
                    4637,
                    4638,
                    4639,
                    4641,
                    4642,
                    4643,
                    4644,
                    4645,
                    4646,
                    4647,
                    4648,
                    4649,
                    4651,
                    4652,
                    4661,
                    4662,
                    4663,
                    4664,
                    4665,
                    4666,
                    4669,
                    4671,
                    4672,
                    4673,
                    4674,
                    4675,
                    4676,
                    4677,
                    4690,
                    4711,
                    4719,
                    4721,
                    4722,
                    4723,
                    4724,
                    4725,
                    4726,
                    4729,
                    4730,
                    4741,
                    4742,
                    4743,
                    4751,
                    4752,
                    4753,
                    4754,
                    4759,
                    4761,
                    4762,
                    4763,
                    4764,
                    4765,
                    4771,
                    4772,
                    4773,
                    4774,
                    4775,
                    4776,
                    4777,
                    4778,
                    4779,
                    4781,
                    4782,
                    4789,
                    4791,
                    4799,
                    4910,
                    4920,
                    4931,
                    4932,
                    4939,
                    4941,
                    4942,
                    4950,
                    5010,
                    5020,
                    5030,
                    5040,
                    5110,
                    5121,
                    5122,
                    5210,
                    5221,
                    5222,
                    5223,
                    5224,
                    5229,
                    5310,
                    5320,
                    5510,
                    5520,
                    5530,
                    5590,
                    5610,
                    5621,
                    5629,
                    5630,
                    5811,
                    5812,
                    5813,
                    5814,
                    5819,
                    5821,
                    5829,
                    5912,
                    5914,
                    5915,
                    5916,
                    5917,
                    5918,
                    5920,
                    6010,
                    6020,
                    6110,
                    6120,
                    6130,
                    6190,
                    6201,
                    6202,
                    6203,
                    6209,
                    6311,
                    6312,
                    6391,
                    6399,
                    6411,
                    6419,
                    6420,
                    6430,
                    6491,
                    6492,
                    6499,
                    6511,
                    6512,
                    6520,
                    6530,
                    6611,
                    6612,
                    6619,
                    6621,
                    6622,
                    6629,
                    6630,
                    6810,
                    6820,
                    6831,
                    6832,
                    6910,
                    6920,
                    7010,
                    7021,
                    7022,
                    7111,
                    7112,
                    7120,
                    7211,
                    7219,
                    7220,
                    7311,
                    7312,
                    7320,
                    7410,
                    7420,
                    7430,
                    7490,
                    7500,
                    7711,
                    7712,
                    7721,
                    7722,
                    7729,
                    7731,
                    7732,
                    7733,
                    7734,
                    7735,
                    7739,
                    7740,
                    7810,
                    7820,
                    7830,
                    7911,
                    7912,
                    7990,
                    8010,
                    8020,
                    8030,
                    8110,
                    8121,
                    8122,
                    8129,
                    8130,
                    8211,
                    8219,
                    8220,
                    8230,
                    8291,
                    8292,
                    8299,
                    8411,
                    8412,
                    8413,
                    8421,
                    8422,
                    8423,
                    8424,
                    8425,
                    8430,
                    8510,
                    8520,
                    8531,
                    8532,
                    8541,
                    8543,
                    8544,
                    8551,
                    8552,
                    8553,
                    8559,
                    8560,
                    8610,
                    8621,
                    8622,
                    8623,
                    8690,
                    8710,
                    8720,
                    8731,
                    8732,
                    8790,
                    8811,
                    8812,
                    8891,
                    8899,
                    9001,
                    9002,
                    9003,
                    9004,
                    9102,
                    9103,
                    9104,
                    9105,
                    9106,
                    9200,
                    9311,
                    9312,
                    9313,
                    9319,
                    9321,
                    9329,
                    9411,
                    9412,
                    9420,
                    9491,
                    9492,
                    9499,
                    9511,
                    9512,
                    9521,
                    9522,
                    9523,
                    9524,
                    9525,
                    9529,
                    9601,
                    9602,
                    9603,
                    9604,
                    9609,
                    9700,
                    9810,
                    9820,
                    9900
                ),
                labels = c(
                    "Growing of cereals (except rice), leguminous crops and oil seeds",
                    "Growing of rice",
                    "Growing of vegetables and melons, roots and tubers",
                    "Growing of sugar cane",
                    "Growing of tobacco",
                    "Growing of fibre crops",
                    "Growing of other non-perennial crops",
                    "Growing of grapes",
                    "Growing of tropical and subtropical fruits",
                    "Growing of citrus fruits",
                    "Growing of pome fruits and stone fruits",
                    "Growing of other tree and bush fruits and nuts",
                    "Growing of oleaginous fruits",
                    "Growing of beverage crops",
                    "Growing of spices, aromatic, drug and pharmaceutical crops",
                    "Growing of other perennial crops",
                    "Plant propagation",
                    "Raising of dairy cattle",
                    "Raising of other cattle and buffaloes",
                    "Raising of horses and other equines",
                    "Raising of camels and camelids",
                    "Raising of sheep and goats",
                    "Raising of swine/pigs",
                    "Raising of poultry",
                    "Raising of other animals",
                    "Mixed farming",
                    "Support activities for crop production",
                    "Support activities for animal production",
                    "Post-harvest crop activities",
                    "Seed processing for propagation",
                    "Hunting, trapping and related service activities",
                    "Silviculture and other forestry activities",
                    "Logging",
                    "Gathering of wild growing non-wood products",
                    "Support services to forestry",
                    "Marine fishing",
                    "Freshwater fishing",
                    "Marine aquaculture",
                    "Freshwater aquaculture",
                    "Mining of hard coal",
                    "Mining of lignite",
                    "Extraction of crude petroleum",
                    "Extraction of natural gas",
                    "Mining of iron ores",
                    "Mining of uranium and thorium ores",
                    "Mining of other non-ferrous metal ores",
                    "Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate",
                    "Operation of gravel and sand pits; mining of clays and kaolin",
                    "Mining of chemical and fertiliser minerals",
                    "Extraction of peat",
                    "Extraction of salt",
                    "Other mining and quarrying n.e.c.",
                    "Support activities for petroleum and natural gas extraction",
                    "Support activities for other mining and quarrying",
                    "Processing and preserving of meat",
                    "Processing and preserving of poultry meat",
                    "Production of meat and poultry meat products",
                    "Processing of fish, crustaceans and molluscs",
                    "Manufacture of canned and preserved fish",
                    "Processing and preserving of potatoes",
                    "Manufacture of fruit and vegetable juice",
                    "Other processing and preserving of fruit and vegetables",
                    "Manufacture of margarine and similar edible fats",
                    "Manufacture of olive oil",
                    "Manufacture of other kind of oils and fats",
                    "Manufacture of ice cream",
                    "Manufacture of cheese",
                    "Operation of dairies",
                    "Manufacture of grain mill products",
                    "Manufacture of starches and starch products",
                    "Manufacture of bread; manufacture of fresh pastry goods and cakes",
                    "Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes",
                    "Manufacture of macaroni, noodles, couscous and similar farinaceous products",
                    "Manufacture of sugar",
                    "Manufacture of cocoa, chocolate and sugar confectionery",
                    "Processing of tea and coffee",
                    "Manufacture of condiments and seasonings",
                    "Manufacture of prepared meals and dishes",
                    "Manufacture of homogenised food preparations and dietetic food",
                    "Manufacture of other food products n.e.c.",
                    "Manufacture of prepared feeds for farm animals",
                    "Manufacture of prepared pet foods",
                    "Distilling, rectifying and blending of spirits",
                    "Manufacture of wine from grape",
                    "Manufacture of cider and other fruit wines",
                    "Manufacture of other non-distilled fermented beverages",
                    "Manufacture of beer",
                    "Manufacture of malt",
                    "Manufacture of soft drinks; production of mineral waters and other bottled waters",
                    "Manufacture of tobacco products",
                    "Preparation and spinning of textile fibres",
                    "Weaving of textiles",
                    "Finishing of textiles",
                    "Manufacture of knitted and crocheted fabrics",
                    "Manufacture of made-up textile articles, except apparel",
                    "Manufacture of carpets and rugs",
                    "Manufacture of cordage, rope, twine and netting",
                    "Manufacture of non-wovens and articles made from non-wovens, except apparel",
                    "Manufacture of other technical and industrial textiles",
                    "Manufacture of other textiles n.e.c.",
                    "Manufacture of leather clothes",
                    "Manufacture of workwear",
                    "Manufacture of other outerwear",
                    "Manufacture of underwear",
                    "Manufacture of other wearing apparel and accessories",
                    "Manufacture of articles of fur",
                    "Manufacture of knitted and crocheted hosiery",
                    "Manufacture of other knitted and crocheted apparel",
                    "Tanning and dressing of leather; dressing and dyeing of fur",
                    "Manufacture of luggage, handbags and the like, saddlery and harness",
                    "Manufacture of footwear",
                    "Sawmilling and planing of wood",
                    "Manufacture of veneer sheets and wood-based panels",
                    "Manufacture of assembled parquet floors",
                    "Manufacture of other builders' carpentry and joinery",
                    "Manufacture of wooden containers",
                    "Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials",
                    "Manufacture of pulp",
                    "Manufacture of paper and paperboard",
                    "Manufacture of corrugated paper and paperboard and of containers of paper and paperboard",
                    "Manufacture of household and sanitary goods and of toilet requisites",
                    "Manufacture of paper stationery",
                    "Manufacture of wallpaper",
                    "Manufacture of other articles of paper and paperboard",
                    "Printing of newspapers",
                    "Other printing",
                    "Pre-press and pre-media services",
                    "Binding and related services",
                    "Reproduction of recorded media",
                    "Manufacture of coke oven products",
                    "Manufacture of refined petroleum products",
                    "Manufacture of industrial gases",
                    "Manufacture of dyes and pigments",
                    "Manufacture of other inorganic basic chemicals",
                    "Manufacture of other organic basic chemicals",
                    "Manufacture of fertilisers and nitrogen compounds",
                    "Manufacture of plastics in primary forms",
                    "Manufacture of synthetic rubber in primary forms",
                    "Manufacture of pesticides and other agrochemical products",
                    "Manufacture of paints, varnishes and similar coatings, printing ink and mastics",
                    "Manufacture of soap and detergents, cleaning and polishing preparations",
                    "Manufacture of perfumes and toilet preparations",
                    "Manufacture of explosives",
                    "Manufacture of glues",
                    "Manufacture of essential oils",
                    "Manufacture of other chemical products n.e.c.",
                    "Manufacture of man-made fibres",
                    "Manufacture of basic pharmaceutical products",
                    "Manufacture of pharmaceutical preparations",
                    "Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres",
                    "Manufacture of other rubber products",
                    "Manufacture of plastic plates, sheets, tubes and profiles",
                    "Manufacture of plastic packing goods",
                    "Manufacture of builders’ ware of plastic",
                    "Manufacture of other plastic products",
                    "Manufacture of flat glass",
                    "Shaping and processing of flat glass",
                    "Manufacture of hollow glass",
                    "Manufacture of glass fibres",
                    "Manufacture and processing of other glass, including technical glassware",
                    "Manufacture of refractory products",
                    "Manufacture of ceramic tiles and flags",
                    "Manufacture of bricks, tiles and construction products, in baked clay",
                    "Manufacture of ceramic household and ornamental articles",
                    "Manufacture of ceramic sanitary fixtures",
                    "Manufacture of ceramic insulators and insulating fittings",
                    "Manufacture of other technical ceramic products",
                    "Manufacture of other ceramic products",
                    "Manufacture of cement",
                    "Manufacture of lime and plaster",
                    "Manufacture of concrete products for construction purposes",
                    "Manufacture of plaster products for construction purposes",
                    "Manufacture of ready-mixed concrete",
                    "Manufacture of mortars",
                    "Manufacture of fibre cement",
                    "Manufacture of other articles of concrete, plaster and cement",
                    "Cutting, shaping and finishing of stone",
                    "Production of abrasive products",
                    "Manufacture of other non-metallic mineral products n.e.c.",
                    "Manufacture of basic iron and steel and of ferro-alloys",
                    "Manufacture of tubes, pipes, hollow profiles and related fittings, of steel",
                    "Cold drawing of bars",
                    "Cold rolling of narrow strip",
                    "Cold forming or folding",
                    "Cold drawing of wire",
                    "Precious metals production",
                    "Aluminium production",
                    "Lead, zinc and tin production",
                    "Copper production",
                    "Other non-ferrous metal production",
                    "Processing of nuclear fuel",
                    "Casting of iron",
                    "Casting of steel",
                    "Casting of light metals",
                    "Casting of other non-ferrous metals",
                    "Manufacture of metal structures and parts of structures",
                    "Manufacture of doors and windows of metal",
                    "Manufacture of central heating radiators and boilers",
                    "Manufacture of other tanks, reservoirs and containers of metal",
                    "Manufacture of steam generators, except central heating hot water boilers",
                    "Manufacture of weapons and ammunition",
                    "Forging, pressing, stamping and roll-forming of metal; powder metallurgy",
                    "Treatment and coating of metals",
                    "Machining",
                    "Manufacture of cutlery",
                    "Manufacture of locks and hinges",
                    "Manufacture of tools",
                    "Manufacture of steel drums and similar containers",
                    "Manufacture of light metal packaging",
                    "Manufacture of wire products, chain and springs",
                    "Manufacture of fasteners and screw machine products",
                    "Manufacture of other fabricated metal products n.e.c.",
                    "Manufacture of electronic components",
                    "Manufacture of loaded electronic boards",
                    "Manufacture of computers and peripheral equipment",
                    "Manufacture of communication equipment",
                    "Manufacture of consumer electronics",
                    "Manufacture of instruments and appliances for measuring, testing and navigation",
                    "Manufacture of watches and clocks",
                    "Manufacture of irradiation, electromedical and electrotherapeutic equipment",
                    "Manufacture of optical instruments and photographic equipment",
                    "Manufacture of magnetic and optical media",
                    "Manufacture of electric motors, generators and transformers",
                    "Manufacture of electricity distribution and control apparatus",
                    "Manufacture of batteries and accumulators",
                    "Manufacture of fibre optic cables",
                    "Manufacture of other electronic and electric wires and cables",
                    "Manufacture of wiring devices",
                    "Manufacture of electric lighting equipment",
                    "Manufacture of electric domestic appliances",
                    "Manufacture of non-electric domestic appliances",
                    "Manufacture of other electrical equipment",
                    "Manufacture of engines and turbines, except aircraft, vehicle and cycle engines",
                    "Manufacture of fluid power equipment",
                    "Manufacture of other pumps and compressors",
                    "Manufacture of other taps and valves",
                    "Manufacture of bearings, gears, gearing and driving elements",
                    "Manufacture of ovens, furnaces and furnace burners",
                    "Manufacture of lifting and handling equipment",
                    "Manufacture of office machinery and equipment (except computers and peripheral equipment)",
                    "Manufacture of power-driven hand tools",
                    "Manufacture of non-domestic cooling and ventilation equipment",
                    "Manufacture of other general-purpose machinery n.e.c.",
                    "Manufacture of agricultural and forestry machinery",
                    "Manufacture of metal forming machinery",
                    "Manufacture of other machine tools",
                    "Manufacture of machinery for metallurgy",
                    "Manufacture of machinery for mining, quarrying and construction",
                    "Manufacture of machinery for food, beverage and tobacco processing",
                    "Manufacture of machinery for textile, apparel and leather production",
                    "Manufacture of machinery for paper and paperboard production",
                    "Manufacture of plastics and rubber machinery",
                    "Manufacture of other special-purpose machinery n.e.c.",
                    "Manufacture of motor vehicles",
                    "Manufacture of bodies (coachwork) for motor vehicles; manufacture of trailers and semi-trailers",
                    "Manufacture of electrical and electronic equipment for motor vehicles",
                    "Manufacture of other parts and accessories for motor vehicles",
                    "Building of ships and floating structures",
                    "Building of pleasure and sporting boats",
                    "Manufacture of railway locomotives and rolling stock",
                    "Manufacture of air and spacecraft and related machinery",
                    "Manufacture of military fighting vehicles",
                    "Manufacture of motorcycles",
                    "Manufacture of bicycles and invalid carriages",
                    "Manufacture of other transport equipment n.e.c.",
                    "Manufacture of office and shop furniture",
                    "Manufacture of kitchen furniture",
                    "Manufacture of mattresses",
                    "Manufacture of other furniture",
                    "Striking of coins",
                    "Manufacture of jewellery and related articles",
                    "Manufacture of imitation jewellery and related articles",
                    "Manufacture of musical instruments",
                    "Manufacture of sports goods",
                    "Manufacture of games and toys",
                    "Manufacture of medical and dental instruments and supplies",
                    "Manufacture of brooms and brushes",
                    "Other manufacturing n.e.c.",
                    "Repair of fabricated metal products",
                    "Repair of machinery",
                    "Repair of electronic and optical equipment",
                    "Repair of electrical equipment",
                    "Repair and maintenance of ships and boats",
                    "Repair and maintenance of aircraft and spacecraft",
                    "Repair and maintenance of other transport equipment",
                    "Repair of other equipment",
                    "Installation of industrial machinery and equipment",
                    "Transmission of electricity",
                    "Distribution of electricity",
                    "Trade of electricity",
                    "Production of hydroelectric power",
                    "Production of conventional thermal power",
                    "Production of nuclear power",
                    "Production of wind power",
                    "Production of electricity from other sources",
                    "Manufacture of gas",
                    "Distribution of gaseous fuels through mains",
                    "Trade of gas through mains",
                    "Steam and air conditioning supply",
                    "Water collection, treatment and supply",
                    "Sewerage",
                    "Collection of non-hazardous waste",
                    "Collection of hazardous waste",
                    "Treatment and disposal of non-hazardous waste",
                    "Treatment and disposal of hazardous waste",
                    "Dismantling of wrecks",
                    "Recovery of sorted materials",
                    "Remediation activities and other waste management services",
                    "Development of building projects",
                    "Construction of residential buildings",
                    "Construction of non-residential buildings",
                    "Construction of roads and motorways",
                    "Construction of railways and underground railways",
                    "Construction of bridges and tunnels",
                    "Construction of utility projects for fluids",
                    "Construction of utility projects for electricity and telecommunications",
                    "Construction of water projects",
                    "Construction of other civil engineering projects n.e.c.",
                    "Demolition",
                    "Site preparation",
                    "Test drilling and boring",
                    "Electrical installation",
                    "Plumbing, heat and air-conditioning installation",
                    "Other construction installation",
                    "Plastering",
                    "Joinery installation",
                    "Floor and wall covering",
                    "Painting and glazing",
                    "Other building completion and finishing",
                    "Roofing activities",
                    "Other specialised construction activities n.e.c.",
                    "Sale of cars and light motor vehicles",
                    "Sale of other motor vehicles",
                    "Maintenance and repair of motor vehicles",
                    "Wholesale trade of motor vehicle parts and accessories",
                    "Retail trade of motor vehicle parts and accessories",
                    "Sale, maintenance and repair of motorcycles and related parts and accessories",
                    "Agents involved in the sale of agricultural raw materials, live animals, textile raw materials and semi-finished goods",
                    "Agents involved in the sale of fuels, ores, metals and industrial chemicals",
                    "Agents involved in the sale of timber and building materials",
                    "Agents involved in the sale of machinery, industrial equipment, ships and aircraft",
                    "Agents involved in the sale of furniture, household goods, hardware and ironmongery",
                    "Agents involved in the sale of textiles, clothing, fur, footwear and leather goods",
                    "Agents involved in the sale of food, beverages and tobacco",
                    "Agents specialised in the sale of other particular products",
                    "Agents involved in the sale of a variety of goods",
                    "Wholesale of grain, unmanufactured tobacco, seeds and animal feeds",
                    "Wholesale of flowers and plants",
                    "Wholesale of live animals",
                    "Wholesale of hides, skins and leather",
                    "Wholesale of fruit and vegetables",
                    "Wholesale of meat and meat products",
                    "Wholesale of dairy products, eggs and edible oils and fats",
                    "Wholesale of beverages",
                    "Wholesale of tobacco products",
                    "Wholesale of sugar and chocolate and sugar confectionery",
                    "Wholesale of coffee, tea, cocoa and spices",
                    "Wholesale of other food, including fish, crustaceans and molluscs",
                    "Non-specialised wholesale of food, beverages and tobacco",
                    "Wholesale of textiles",
                    "Wholesale of clothing and footwear",
                    "Wholesale of electrical household appliances",
                    "Wholesale of china and glassware and cleaning materials",
                    "Wholesale of perfume and cosmetics",
                    "Wholesale of pharmaceutical goods",
                    "Wholesale of furniture, carpets and lighting equipment",
                    "Wholesale of watches and jewellery",
                    "Wholesale of other household goods",
                    "Wholesale of computers, computer peripheral equipment and software",
                    "Wholesale of electronic and telecommunications equipment and parts",
                    "Wholesale of agricultural machinery, equipment and supplies",
                    "Wholesale of machine tools",
                    "Wholesale of mining, construction and civil engineering machinery",
                    "Wholesale of machinery for the textile industry and of sewing and knitting machines",
                    "Wholesale of office furniture",
                    "Wholesale of other office machinery and equipment",
                    "Wholesale of other machinery and equipment",
                    "Wholesale of solid, liquid and gaseous fuels and related products",
                    "Wholesale of metals and metal ores",
                    "Wholesale of wood, construction materials and sanitary equipment",
                    "Wholesale of hardware, plumbing and heating equipment and supplies",
                    "Wholesale of chemical products",
                    "Wholesale of other intermediate products",
                    "Wholesale of waste and scrap",
                    "Non-specialised wholesale trade",
                    "Retail sale in non-specialised stores with food, beverages or tobacco predominating",
                    "Other retail sale in non-specialised stores",
                    "Retail sale of fruit and vegetables in specialised stores",
                    "Retail sale of meat and meat products in specialised stores",
                    "Retail sale of fish, crustaceans and molluscs in specialised stores",
                    "Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores",
                    "Retail sale of beverages in specialised stores",
                    "Retail sale of tobacco products in specialised stores",
                    "Other retail sale of food in specialised stores",
                    "Retail sale of automotive fuel in specialised stores",
                    "Retail sale of computers, peripheral units and software in specialised stores",
                    "Retail sale of telecommunications equipment in specialised stores",
                    "Retail sale of audio and video equipment in specialised stores",
                    "Retail sale of textiles in specialised stores",
                    "Retail sale of hardware, paints and glass in specialised stores",
                    "Retail sale of carpets, rugs, wall and floor coverings in specialised stores",
                    "Retail sale of electrical household appliances in specialised stores",
                    "Retail sale of furniture, lighting equipment and other household articles in specialised stores",
                    "Retail sale of books in specialised stores",
                    "Retail sale of newspapers and stationery in specialised stores",
                    "Retail sale of music and video recordings in specialised stores",
                    "Retail sale of sporting equipment in specialised stores",
                    "Retail sale of games and toys in specialised stores",
                    "Retail sale of clothing in specialised stores",
                    "Retail sale of footwear and leather goods in specialised stores",
                    "Dispensing chemist in specialised stores",
                    "Retail sale of medical and orthopaedic goods in specialised stores",
                    "Retail sale of cosmetic and toilet articles in specialised stores",
                    "Retail sale of flowers, plants, seeds, fertilisers, pet animals and pet food in specialised stores",
                    "Retail sale of watches and jewellery in specialised stores",
                    "Other retail sale of new goods in specialised stores",
                    "Retail sale of second-hand goods in stores",
                    "Retail sale via stalls and markets of food, beverages and tobacco products",
                    "Retail sale via stalls and markets of textiles, clothing and footwear",
                    "Retail sale via stalls and markets of other goods",
                    "Retail sale via mail order houses or via Internet",
                    "Other retail sale not in stores, stalls or markets",
                    "Passenger rail transport, interurban",
                    "Freight rail transport",
                    "Urban and suburban passenger land transport",
                    "Taxi operation",
                    "Other passenger land transport n.e.c.",
                    "Freight transport by road",
                    "Removal services",
                    "Transport via pipeline",
                    "Sea and coastal passenger water transport",
                    "Sea and coastal freight water transport",
                    "Inland passenger water transport",
                    "Inland freight water transport",
                    "Passenger air transport",
                    "Freight air transport",
                    "Space transport",
                    "Warehousing and storage",
                    "Service activities incidental to land transportation",
                    "Service activities incidental to water transportation",
                    "Service activities incidental to air transportation",
                    "Cargo handling",
                    "Other transportation support activities",
                    "Postal activities under universal service obligation",
                    "Other postal and courier activities",
                    "Hotels and similar accommodation",
                    "Holiday and other short-stay accommodation",
                    "Camping grounds, recreational vehicle parks and trailer parks",
                    "Other accommodation",
                    "Restaurants and mobile food service activities",
                    "Event catering activities",
                    "Other food service activities",
                    "Beverage serving activities",
                    "Book publishing",
                    "Publishing of directories and mailing lists",
                    "Publishing of newspapers",
                    "Publishing of journals and periodicals",
                    "Other publishing activities",
                    "Publishing of computer games",
                    "Other software publishing",
                    "Motion picture, video and television programme post-production activities",
                    "Motion picture projection activities",
                    "Motion picture and video production activities",
                    "Television programme production activities",
                    "Motion picture and video distribution activities",
                    "Television programme distribution activities",
                    "Sound recording and music publishing activities",
                    "Radio broadcasting",
                    "Television programming and broadcasting activities",
                    "Wired telecommunications activities",
                    "Wireless telecommunications activities",
                    "Satellite telecommunications activities",
                    "Other telecommunications activities",
                    "Computer programming activities",
                    "Computer consultancy activities",
                    "Computer facilities management activities",
                    "Other information technology and computer service activities",
                    "Data processing, hosting and related activities",
                    "Web portals",
                    "News agency activities",
                    "Other information service activities n.e.c.",
                    "Central banking",
                    "Other monetary intermediation",
                    "Activities of holding companies",
                    "Trusts, funds and similar financial entities",
                    "Financial leasing",
                    "Other credit granting",
                    "Other financial service activities, except insurance and pension funding n.e.c.",
                    "Life insurance",
                    "Non-life insurance",
                    "Reinsurance",
                    "Pension funding",
                    "Administration of financial markets",
                    "Security and commodity contracts brokerage",
                    "Other activities auxiliary to financial services, except insurance and pension funding",
                    "Risk and damage evaluation",
                    "Activities of insurance agents and brokers",
                    "Other activities auxiliary to insurance and pension funding",
                    "Fund management activities",
                    "Buying and selling of own real estate",
                    "Rental and operating of own or leased real estate",
                    "Real estate agencies",
                    "Management of real estate on a fee or contract basis",
                    "Legal activities",
                    "Accounting, bookkeeping and auditing activities; tax consultancy",
                    "Activities of head offices",
                    "Public relations and communication activities",
                    "Business and other management consultancy activities",
                    "Architectural activities",
                    "Engineering activities and related technical consultancy",
                    "Technical testing and analysis",
                    "Research and experimental development on biotechnology",
                    "Other research and experimental development on natural sciences and engineering",
                    "Research and experimental development on social sciences and humanities",
                    "Advertising agencies",
                    "Media representation",
                    "Market research and public opinion polling",
                    "Specialised design activities",
                    "Photographic activities",
                    "Translation and interpretation activities",
                    "Other professional, scientific and technical activities n.e.c.",
                    "Veterinary activities",
                    "Rental and leasing of cars and light motor vehicles",
                    "Rental and leasing of trucks",
                    "Rental and leasing of recreational and sports goods",
                    "Rental of video tapes and disks",
                    "Rental and leasing of other personal and household goods",
                    "Rental and leasing of agricultural machinery and equipment",
                    "Rental and leasing of construction and civil engineering machinery and equipment",
                    "Rental and leasing of office machinery and equipment (including computers)",
                    "Rental and leasing of water transport equipment",
                    "Rental and leasing of air transport equipment",
                    "Rental and leasing of other machinery, equipment and tangible goods n.e.c.",
                    "Leasing of intellectual property and similar products, except copyrighted works",
                    "Activities of employment placement agencies",
                    "Temporary employment agency activities",
                    "Other human resources provision",
                    "Travel agency activities",
                    "Tour operator activities",
                    "Other reservation service and related activities",
                    "Private security activities",
                    "Security systems service activities",
                    "Investigation activities",
                    "Combined facilities support activities",
                    "General cleaning of buildings",
                    "Other building and industrial cleaning activities",
                    "Other cleaning activities",
                    "Landscape service activities",
                    "Combined office administrative service activities",
                    "Photocopying, document preparation and other specialised office support activities",
                    "Activities of call centres",
                    "Organisation of conventions and trade shows",
                    "Activities of collection agencies and credit bureaus",
                    "Packaging activities",
                    "Other business support service activities n.e.c.",
                    "General public administration activities",
                    "Regulation of the activities of providing health care, education, cultural services and other social services, excluding social security",
                    "Regulation of and contribution to more efficient operation of businesses",
                    "Foreign affairs",
                    "Defence activities",
                    "Justice and judicial activities",
                    "Public order and safety activities",
                    "Fire service activities",
                    "Compulsory social security activities",
                    "Pre-primary education",
                    "Primary education",
                    "General secondary education",
                    "Technical and vocational secondary education",
                    "Post-secondary non-tertiary education",
                    "University education",
                    "Non-university tertiary education",
                    "Sports and recreation education",
                    "Cultural education",
                    "Driving school activities",
                    "Other education n.e.c.",
                    "Educational support activities",
                    "Hospital activities",
                    "General medical practice activities",
                    "Specialist medical practice activities",
                    "Dental practice activities",
                    "Other human health activities",
                    "Residential nursing care activities",
                    "Residential care activities for mental retardation, mental health and substance abuse",
                    "Residential care activities for the elderly",
                    "Residential care activities for the disabled",
                    "Other residential care activities",
                    "Social work activities without accommodation for the elderly",
                    "Social work activities without accommodation for the disabled",
                    "Child day-care activities",
                    "Other social work activities without accommodation n.e.c.",
                    "Performing arts",
                    "Support activities to performing arts",
                    "Artistic creation",
                    "Operation of arts facilities",
                    "Museums activities",
                    "Operation of historical sites and buildings and similar visitor attractions",
                    "Botanical and zoological gardens and nature reserves activities",
                    "Libraries activities",
                    "Archives activities",
                    "Gambling and betting activities",
                    "Operation of sports facilities",
                    "Activities of sports clubs",
                    "Fitness facilities",
                    "Other sports activities",
                    "Activities of amusement parks and theme parks",
                    "Other amusement and recreation activities",
                    "Activities of business and employers membership organisations",
                    "Activities of professional membership organisations",
                    "Activities of trade unions",
                    "Activities of religious organisations",
                    "Activities of political organisations",
                    "Activities of other membership organisations n.e.c.",
                    "Repair of computers and peripheral equipment",
                    "Repair of communication equipment",
                    "Repair of consumer electronics",
                    "Repair of household appliances and home and garden equipment",
                    "Repair of footwear and leather goods",
                    "Repair of furniture and home furnishings",
                    "Repair of watches, clocks and jewellery",
                    "Repair of other personal and household goods",
                    "Washing and (dry-)cleaning of textile and fur products",
                    "Hairdressing and other beauty treatment",
                    "Funeral and related activities",
                    "Physical well-being activities",
                    "Other personal service activities n.e.c.",
                    "Activities of households as employers of domestic personnel",
                    "Undifferentiated goods-producing activities of private households for own use",
                    "Undifferentiated service-producing activities of private households for own use",
                    "Activities of extraterritorial organisations and bodies"
                )
        )
    }

return(V)
}